name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc6e2f290a6faa950ac6365228a02c367490dfacb7a5e67f1e5261a714afe218"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
