name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b8a6a4c7a83bd142a35e853fa167db806a79f692be5cb3c487c2e48e08873aa"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
