name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed1b0be106fd68039f0192ebede9cc9240b65af0957d1dbd8ad3e540254b8aab"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
