name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b4f127dccc807a6fbfb1f04e7af8132de5e9cee32145917ee6594d9ba2d807"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
