name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fde88d17ff0b93d6454f99b3486bc95dbd0a6637e5c12398d7a52da06d06aeb7"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
