name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b94cb81588d4bef5892be16c22e2bf5c0dd2a6b5af7fbec1d1f32e07d524cc7"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
