name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60be7b42b8e69dc980b409cb7e3b8bcc2d6011041c2fa88242d1abdc487d6747"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
