name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e1da69300afeadaf2b9087577b621d1580bd3f85e6f4bfec27f62786e245f31"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
