name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75c36c82755a5bbfaea301e6d0a88dad548fb7bc727c42a974f67b02a8d697f8"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
