name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8ce1a664dcd7904d14d4de79845456663df39f6529c648ced993ac2d4281b2e"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
