name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cbdb4a9689efd58192ef18b5812eb12dc930a5ec383c3245e55de4547737ef5"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
