name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b23fa9998f42a755a24ffbf479fe7e964d0881f5bbbfaece42dd406080c370"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
