name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46049d7d6981d6243cc49a808dd224d62cf9ac1f1911bf134eedf6c3ee0bf296"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
