name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80d4bdcb09f67c077dc938cb21716907cef80a7d1d41de910e70e2bdd87e129d"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
