name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cac1df56d65b2d181c0c24428e82a269b33804fcd1ef40c8278f7cab8c573d9"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
