name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a4715ffee34184fb28ba1d9318dea090cb9d5e6a1f21cbc0204b7ddbf3a8555"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
