name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7757eaf8de723f10a3f6ff467f931e968dabd340d775b1564b7a3f5a3c6619b9"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
