name = "Dartis-Craft-Vanilla-Plus-Ultra-1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5e2328c29b59a8d6c9ad77404034a6487cf514d78b161afbceb90e906c0151f"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
