name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.659.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3433/495/CraftTweaker2-1.12-4.1.20.659.jar"
hash-format = "murmur2"
hash = "2599218729"

[update]
[update.curseforge]
file-id = 3433495
project-id = 239197
release-channel = "beta"
