name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.669.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3515/80/CraftTweaker2-1.12-4.1.20.669.jar"
hash-format = "murmur2"
hash = "2204060448"

[update]
[update.curseforge]
file-id = 3515080
project-id = 239197
release-channel = "beta"
