name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.674.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3642/364/CraftTweaker2-1.12-4.1.20.674.jar"
hash-format = "murmur2"
hash = "227849568"

[update]
[update.curseforge]
file-id = 3642364
project-id = 239197
release-channel = "beta"
