name = "Enchanting Plus"
filename = "EnchantingPlus-1.12.2-5.0.176.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2664/227/EnchantingPlus-1.12.2-5.0.176.jar"
hash-format = "murmur2"
hash = "318562578"

[update]
[update.curseforge]
file-id = 2664227
project-id = 59413
release-channel = "beta"
