name = "Enchanting Plus"
filename = "EnchantingPlus-1.12.2-5.0.179.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2724/705/EnchantingPlus-1.12.2-5.0.179.jar"
hash-format = "murmur2"
hash = "3335987454"

[update]
[update.curseforge]
file-id = 2724705
project-id = 59413
release-channel = "beta"
