name = "Ender IO"
filename = "EnderIO-1.12.2-5.2.64.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3121/534/EnderIO-1.12.2-5.2.64.jar"
hash-format = "murmur2"
hash = "907018018"

[update]
[update.curseforge]
file-id = 3121534
project-id = 64578
release-channel = "beta"
