name = "Hunting Dimension"
filename = "HuntingDimension-1.12.2-1.0.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2827/888/HuntingDimension-1.12.2-1.0.42.jar"
hash-format = "murmur2"
hash = "2247388121"

[update]
[update.curseforge]
file-id = 2827888
project-id = 283235
release-channel = "beta"
