name = "JEI Hider"
filename = "JEIHider-1.1c.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2633/243/JEIHider-1.1c.jar"
hash-format = "murmur2"
hash = "3105393364"

[update]
[update.curseforge]
file-id = 2633243
project-id = 247070
