name = "Lucraft: Core"
filename = "LucraftCore-1.12.2-2.4.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3380/490/LucraftCore-1.12.2-2.4.16.jar"
hash-format = "murmur2"
hash = "24877450"

[update]
[update.curseforge]
file-id = 3380490
project-id = 230651
release-channel = "beta"
