name = "Natura"
filename = "natura-1.12.2-4.3.2.69.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2711/439/natura-1.12.2-4.3.2.69.jar"
hash-format = "murmur2"
hash = "2375561468"

[update]
[update.curseforge]
file-id = 2711439
project-id = 74120
release-channel = "beta"
