name = "Nether+"
filename = "nether+-2.0.0-open-beta1-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3109/172/nether+-2.0.0-open-beta1-1.12.2.jar"
hash-format = "murmur2"
hash = "2460560829"

[update]
[update.curseforge]
file-id = 3109172
project-id = 361620
release-channel = "beta"
