name = "Oreberries"
filename = "oreberries-1.12.x-0.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2578/45/oreberries-1.12.x-0.5.0.jar"
hash-format = "murmur2"
hash = "1814015962"

[update]
[update.curseforge]
file-id = 2578045
project-id = 275408
release-channel = "beta"
