name = "Prefab"
filename = "prefab-1.3.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3576/641/prefab-1.3.1.5.jar"
hash-format = "murmur2"
hash = "2467715327"

[update]
[update.curseforge]
file-id = 3576641
project-id = 246550
release-channel = "beta"
