name = "Prefab"
filename = "prefab-1.3.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3368/264/prefab-1.3.1.2.jar"
hash-format = "murmur2"
hash = "2786447363"

[update]
[update.curseforge]
file-id = 3368264
project-id = 246550
release-channel = "beta"
