name = "Prefab"
filename = "prefab-1.3.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3503/933/prefab-1.3.1.4.jar"
hash-format = "murmur2"
hash = "1149259196"

[update]
[update.curseforge]
file-id = 3503933
project-id = 246550
release-channel = "beta"
