name = "UniDict"
filename = "UniDict-1.12.2-3.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3162/137/UniDict-1.12.2-3.0.4.jar"
hash-format = "murmur2"
hash = "2716407916"

[update]
[update.curseforge]
file-id = 3162137
project-id = 244258
release-channel = "beta"
