name = "WanionLib"
filename = "WanionLib-1.12.2-2.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3558/524/WanionLib-1.12.2-2.7.jar"
hash-format = "murmur2"
hash = "3486510525"

[update]
[update.curseforge]
file-id = 3558524
project-id = 253043
release-channel = "beta"
