name = "WanionLib"
filename = "WanionLib-1.12.2-2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3553/625/WanionLib-1.12.2-2.6.jar"
hash-format = "murmur2"
hash = "1902961597"

[update]
[update.curseforge]
file-id = 3553625
project-id = 253043
release-channel = "beta"
